# MCU name
MCU = RP2040

# Bootloader selection
BOOTLOADER = rp2040

# RP2040-specific options
ALLOW_WARNINGS = yes
PICO_INTRINSICS_ENABLED = no # ATM Unsupported by ChibiOS.

SERIAL_DRIVER = vendor

# Pointing device
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = azoteq_iqs5xx
POINTING_DEVICE_DRIVER = cirque_pinnacle_spi
I2C_DRIVER_REQUIRED = yes
SPI_DRIVER_REQUIRED = yes

# Split keyboard options
OS_DETECTION_ENABLE = yes
CHIBIOS_OS_ENABLE = yes
SPLIT_USB_DETECT = yes
SPLIT_TRANSPORT_ENABLE = yes

TAP_DANCE_ENABLE = yes

# RGB options
WS2812_DRIVER = vendor

RGBLIGHT_ENABLE = yes
RGBLIGHT_DRIVER = ws2812
RGBLIGHT_SUPPORTED = yes