
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = cirque_pinnacle_i2c
I2C_DRIVER_REQUIRED = yes

OS_DETECTION_ENABLE = yes

WS2812_DRIVER = vendor

RGBLIGHT_ENABLE = yes
RGBLIGHT_DRIVER = ws2812
RGBLIGHT_SUPPORTED = yes
