MOUSEKEY_ENABLE = yes

ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pmw3389
SPI_DRIVER_REQUIRED = yes

OS_DETECTION_ENABLE = yes

WS2812_DRIVER = vendor

RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = ws2812
RGB_MATRIX_SUPPORTED = yes
RGBLIGHT_SUPPORTED = yes
